language: node_js

node_js:
  - '18'

addons:
  chrome: stable

branches:
  only:
    - master

cache:
  directories:
    - ./node_modules

install:
  - npm ci

script:
  - ng test --watch false --no-progress --browsers ChromeHeadless
